-- NAKA License Cloud enterprise migration
-- Jalankan sekali di Supabase SQL Editor menggunakan project owner.

create table if not exists public.licenses (
  owner_id text not null,
  owner_type text not null,
  product text not null,
  status text not null default 'active',
  expires_at timestamptz,
  created_at timestamptz not null default now()
);

create table if not exists public.installations (
  owner_id text not null,
  owner_type text not null default 'User',
  product text not null,
  place_id text not null,
  universe_id text,
  place_name text,
  game_name text,
  job_id text,
  player_count integer,
  max_players integer,
  is_private_server boolean,
  is_studio boolean,
  system_version text,
  first_seen_at timestamptz not null default now(),
  last_seen_at timestamptz not null default now()
);

alter table public.licenses
  add column if not exists license_key_hash text,
  add column if not exists universe_id text,
  add column if not exists activated_at timestamptz,
  add column if not exists customer_name text,
  add column if not exists notes text,
  add column if not exists compromised_at timestamptz,
  add column if not exists updated_at timestamptz default now();

alter table public.installations
  add column if not exists owner_type text default 'User',
  add column if not exists universe_id text,
  add column if not exists place_name text,
  add column if not exists game_name text,
  add column if not exists job_id text,
  add column if not exists player_count integer,
  add column if not exists max_players integer,
  add column if not exists is_private_server boolean,
  add column if not exists is_studio boolean,
  add column if not exists system_version text,
  add column if not exists first_seen_at timestamptz default now(),
  add column if not exists last_seen_at timestamptz default now();

create unique index if not exists licenses_owner_product_unique
  on public.licenses (owner_id, owner_type, product);

create table if not exists public.access_attempts (
  id bigint generated by default as identity primary key,
  owner_id text,
  owner_type text,
  product text,
  place_id text,
  universe_id text,
  place_name text,
  game_name text,
  system_version text,
  ip_address text,
  user_agent text,
  reason text not null,
  attempted_at timestamptz not null default now()
);
create index if not exists access_attempts_attempted_at_idx on public.access_attempts (attempted_at desc);
create index if not exists access_attempts_owner_idx on public.access_attempts (owner_id, product);
create index if not exists access_attempts_ip_idx on public.access_attempts (ip_address, attempted_at desc);

create table if not exists public.audit_logs (
  id bigint generated by default as identity primary key,
  action text not null,
  target_type text,
  target_id text,
  actor_ip text,
  actor_label text default 'admin',
  before_data jsonb,
  after_data jsonb,
  metadata jsonb,
  created_at timestamptz not null default now()
);
create index if not exists audit_logs_created_at_idx on public.audit_logs (created_at desc);

create table if not exists public.products (
  code text primary key,
  name text not null,
  latest_version text,
  minimum_version text,
  version_policy text not null default 'warn' check (version_policy in ('allow','warn','block')),
  maintenance boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.customer_notes (
  id bigint generated by default as identity primary key,
  owner_id text not null,
  owner_type text not null,
  note text not null,
  created_at timestamptz not null default now()
);
create index if not exists customer_notes_owner_idx on public.customer_notes (owner_id, owner_type, created_at desc);

create unique index if not exists installations_owner_product_place_unique
  on public.installations (owner_id, product, place_id);

alter table public.licenses enable row level security;
alter table public.installations enable row level security;
alter table public.access_attempts enable row level security;
alter table public.audit_logs enable row level security;
alter table public.products enable row level security;
alter table public.customer_notes enable row level security;

-- API server harus memakai SUPABASE service-role key, bukan anon key.
-- Hapus policy publik lama jika pernah dibuat.
