-- Jalankan sekali di Supabase SQL Editor sebelum deploy API baru.

alter table public.licenses
  add column if not exists license_key_hash text,
  add column if not exists universe_id text,
  add column if not exists activated_at timestamptz;

create unique index if not exists licenses_owner_product_unique
  on public.licenses (owner_id, owner_type, product);

create table if not exists public.access_attempts (
  id bigint generated by default as identity primary key,
  owner_id text,
  owner_type text,
  product text,
  place_id text,
  universe_id text,
  place_name text,
  game_name text,
  system_version text,
  ip_address text,
  user_agent text,
  reason text not null,
  attempted_at timestamptz not null default now()
);

create index if not exists access_attempts_attempted_at_idx
  on public.access_attempts (attempted_at desc);

create index if not exists access_attempts_owner_idx
  on public.access_attempts (owner_id, product);

-- Supabase REST upsert verify.js membutuhkan unique constraint ini.
create unique index if not exists installations_owner_product_place_unique
  on public.installations (owner_id, product, place_id);

-- Pastikan client publik tidak dapat membaca tabel secara langsung.
alter table public.licenses enable row level security;
alter table public.installations enable row level security;
alter table public.access_attempts enable row level security;

-- API memakai service-role key dari server. Jangan gunakan anon key sebagai SUPABASE_KEY.
-- Hapus policy publik lama secara manual bila sebelumnya pernah dibuat.
