-- NAKA License Cloud SSS Dashboard migration
alter table public.licenses add column if not exists license_key_hash text;
alter table public.licenses add column if not exists universe_id text;
alter table public.licenses add column if not exists activated_at timestamptz;
alter table public.licenses add column if not exists notes text;

create table if not exists public.admin_audit_logs (
  id bigint generated by default as identity primary key,
  action text not null,
  target text,
  before_data jsonb,
  after_data jsonb,
  metadata jsonb,
  admin_ip text,
  user_agent text,
  created_at timestamptz not null default now()
);
create index if not exists admin_audit_logs_created_idx on public.admin_audit_logs(created_at desc);

create table if not exists public.products (
  id bigint generated by default as identity primary key,
  code text not null unique,
  name text not null,
  latest_version text,
  minimum_version text,
  version_policy text not null default 'warn' check (version_policy in ('allow','warn','block')),
  maintenance boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.access_attempts (
  id bigint generated by default as identity primary key,
  owner_id text, owner_type text, product text, place_id text, universe_id text,
  place_name text, game_name text, system_version text, ip_address text, user_agent text,
  reason text not null, attempted_at timestamptz not null default now()
);
create index if not exists access_attempts_attempted_idx on public.access_attempts(attempted_at desc);
create index if not exists access_attempts_owner_idx on public.access_attempts(owner_id,product);
create unique index if not exists licenses_owner_product_unique on public.licenses(owner_id,owner_type,product);
create unique index if not exists installations_owner_product_place_unique on public.installations(owner_id,product,place_id);

alter table public.admin_audit_logs enable row level security;
alter table public.products enable row level security;
alter table public.access_attempts enable row level security;
-- Gunakan SUPABASE_KEY service_role pada Vercel. Jangan gunakan anon key.
