const clean=(v,n=160)=>v==null?null:String(v).trim().slice(0,n);
const ip=req=>clean(String(req.headers['x-forwarded-for']||'').split(',')[0],80)||clean(req.socket?.remoteAddress,80)||'unknown';
const auth=req=>Boolean(process.env.ADMIN_SECRET&&req.headers['x-admin-secret']===process.env.ADMIN_SECRET);
const base=()=>process.env.SUPABASE_URL;
const key=()=>process.env.SUPABASE_KEY;
async function db(path,opt={}){const r=await fetch(`${base()}/rest/v1/${path}`,{...opt,headers:{apikey:key(),Authorization:`Bearer ${key()}`,'Content-Type':'application/json',...(opt.headers||{})}});const t=await r.text();if(!r.ok)throw new Error(`Supabase ${r.status}: ${t.slice(0,400)}`);return t?JSON.parse(t):null}
async function safe(path){try{return await db(path)}catch{return[]}}
async function audit(req,action,targetType,targetId,beforeData=null,afterData=null,metadata=null){try{await db('audit_logs',{method:'POST',headers:{Prefer:'return=minimal'},body:JSON.stringify({action,target_type:targetType,target_id:targetId,actor_ip:ip(req),before_data:beforeData,after_data:afterData,metadata})})}catch{}}
function cors(req,res){const o=process.env.ADMIN_ORIGIN;if(o&&req.headers.origin===o)res.setHeader('Access-Control-Allow-Origin',o);res.setHeader('Access-Control-Allow-Headers','Content-Type,x-admin-secret');res.setHeader('Access-Control-Allow-Methods','GET,POST,PATCH,DELETE,OPTIONS');res.setHeader('Cache-Control','no-store')}
function riskGroup(rows){const map=new Map();for(const r of rows){const k=`${r.ip_address||'unknown'}|${r.owner_id||'unknown'}|${r.product||'unknown'}`;const g=map.get(k)||{key:k,ip_address:r.ip_address,owner_id:r.owner_id,owner_type:r.owner_type,product:r.product,attempts:0,reasons:new Set(),universes:new Set(),places:new Set(),first_seen:r.attempted_at,last_seen:r.attempted_at};g.attempts++;g.reasons.add(r.reason||'UNKNOWN');if(r.universe_id)g.universes.add(r.universe_id);if(r.place_id)g.places.add(r.place_id);if(new Date(r.attempted_at)<new Date(g.first_seen))g.first_seen=r.attempted_at;if(new Date(r.attempted_at)>new Date(g.last_seen))g.last_seen=r.attempted_at;map.set(k,g)}return[...map.values()].map(g=>{let score=Math.min(45,g.attempts*3)+Math.min(20,g.universes.size*7)+Math.min(15,g.reasons.size*5);if(g.reasons.has('REVOKED')||g.reasons.has('SIGNATURE_INVALID'))score+=20;score=Math.min(100,score);return{...g,reasons:[...g.reasons],universes:[...g.universes],places:[...g.places],risk_score:score,risk_level:score>=80?'critical':score>=55?'high':score>=30?'medium':'low'}}).sort((a,b)=>b.risk_score-a.risk_score)}
export default async function handler(req,res){cors(req,res);if(req.method==='OPTIONS')return res.status(204).end();if(!auth(req))return res.status(401).json({error:'ADMIN_SECRET salah'});if(!base()||!key())return res.status(500).json({error:'Supabase belum dikonfigurasi'});try{
 const u=new URL(req.url,'https://local');const resource=u.searchParams.get('resource')||'overview';
 if(req.method==='GET'){
  if(resource==='overview'){
   const [licenses,installations,attempts,audits,products,notes]=await Promise.all([safe('licenses?select=*&order=created_at.desc'),safe('installations?select=*&order=last_seen_at.desc'),safe('access_attempts?select=*&order=attempted_at.desc&limit=1000'),safe('audit_logs?select=*&order=created_at.desc&limit=200'),safe('products?select=*&order=name.asc'),safe('customer_notes?select=*&order=created_at.desc')]);
   const licenseKeys=new Set(licenses.map(x=>`${x.owner_id}:${x.owner_type}:${x.product}`));const legacy=installations.filter(x=>!licenseKeys.has(`${x.owner_id}:${x.owner_type||'User'}:${x.product}`)).map(x=>({owner_id:x.owner_id,owner_type:x.owner_type||'User',product:x.product,place_id:x.place_id,universe_id:x.universe_id,place_name:x.place_name,game_name:x.game_name,system_version:x.system_version,reason:'LEGACY_NO_LICENSE',attempted_at:x.last_seen_at||x.first_seen_at,ip_address:null,user_agent:null}));const allAttempts=[...attempts,...legacy];
   return res.status(200).json({licenses,installations,attempts:allAttempts,threats:riskGroup(allAttempts),audits,products,notes,server_time:new Date().toISOString()});
  }
  if(resource==='export'){const type=u.searchParams.get('type')||'licenses';const allowed={licenses:'licenses?select=*&order=created_at.desc',installations:'installations?select=*&order=last_seen_at.desc',attempts:'access_attempts?select=*&order=attempted_at.desc',audits:'audit_logs?select=*&order=created_at.desc'};if(!allowed[type])return res.status(400).json({error:'Jenis export tidak valid'});return res.status(200).json({type,data:await safe(allowed[type]),exported_at:new Date().toISOString()})}
 }
 const b=req.body||{};
 if(req.method==='POST'&&resource==='product'){const row={code:clean(b.code,50),name:clean(b.name,100),latest_version:clean(b.latestVersion,30),minimum_version:clean(b.minimumVersion,30),version_policy:['allow','warn','block'].includes(b.versionPolicy)?b.versionPolicy:'warn',maintenance:Boolean(b.maintenance)};if(!row.code||!row.name)return res.status(400).json({error:'Code dan nama produk wajib'});const out=await db('products?on_conflict=code',{method:'POST',headers:{Prefer:'resolution=merge-duplicates,return=representation'},body:JSON.stringify(row)});await audit(req,'PRODUCT_UPSERT','product',row.code,null,row);return res.status(200).json({success:true,product:out?.[0]})}
 if(req.method==='POST'&&resource==='note'){const row={owner_id:clean(b.ownerId,30),owner_type:b.ownerType==='Group'?'Group':'User',note:clean(b.note,1000)};if(!row.owner_id||!row.note)return res.status(400).json({error:'Owner dan catatan wajib'});const out=await db('customer_notes',{method:'POST',headers:{Prefer:'return=representation'},body:JSON.stringify(row)});await audit(req,'CUSTOMER_NOTE_CREATED','customer',`${row.owner_type}:${row.owner_id}`,null,row);return res.status(200).json({success:true,note:out?.[0]})}
 if(req.method==='POST'&&resource==='audit'){await audit(req,clean(b.action,80)||'ADMIN_ACTION',clean(b.targetType,40),clean(b.targetId,120),b.before||null,b.after||null,b.metadata||null);return res.status(200).json({success:true})}
 if(req.method==='PATCH'&&resource==='license'){const owner=clean(b.ownerId,30),type=b.ownerType==='Group'?'Group':'User',product=clean(b.product,50);if(!owner||!product)return res.status(400).json({error:'Identitas lisensi tidak lengkap'});const q=`licenses?owner_id=eq.${encodeURIComponent(owner)}&owner_type=eq.${type}&product=eq.${encodeURIComponent(product)}`;const before=(await safe(`${q}&select=*`))[0]||null;const patch={updated_at:new Date().toISOString()};if(['active','pending','suspended','revoked','compromised'].includes(b.status))patch.status=b.status;if(b.status==='compromised')patch.compromised_at=new Date().toISOString();if(b.customerName!==undefined)patch.customer_name=clean(b.customerName,120);if(b.notes!==undefined)patch.notes=clean(b.notes,1000);const out=await db(q,{method:'PATCH',headers:{Prefer:'return=representation'},body:JSON.stringify(patch)});await audit(req,'LICENSE_UPDATED','license',`${type}:${owner}:${product}`,before,out?.[0]||patch);return res.status(200).json({success:true,license:out?.[0]})}
 return res.status(405).json({error:'Method tidak didukung'});
}catch(e){console.error('[admin-pro]',e);return res.status(502).json({error:'Admin API gagal',detail:e.message})}}
